const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
    const LectureSchedule = sequelize.define('LectureSchedule', {
        // id is auto-generated by Sequelize
        startTime: {
            type: DataTypes.TIME,
            allowNull: false
        },
        endTime: {
            type: DataTypes.TIME,
            allowNull: false
        },
        slotId: {
            type: DataTypes.STRING,
            allowNull: false,
            unique: true // Each slotId should be unique
        },
        timeSlot: {
            type: DataTypes.STRING,
            allowNull: true
        },
        subjectName: {
            type: DataTypes.STRING,
            allowNull: true
        },
        teacherName: {
            type: DataTypes.STRING,
            allowNull: true
        },
        day: {
            type: DataTypes.STRING,
            allowNull: false
        },
        program: {
            type: DataTypes.STRING,
            allowNull: true
        },
        batch: {
            type: DataTypes.STRING,
            allowNull: true
        },
        semester: {
            type: DataTypes.INTEGER,
            allowNull: true
        },
        room: {
            type: DataTypes.STRING,
            allowNull: true
        }
    }, {
        tableName: 'LectureSchedules',
        timestamps: false // Disable createdAt/updatedAt
    });

    return LectureSchedule;
};
